import { Season } from '../../types';

export type CropTemp = 'C' | 'M' | 'H';

export interface CropNeeds {
  tilled?: boolean;            // Requires tilled soil (Farmland / Sand Farmland)
  trellis?: boolean;           // Needs adjacent Trellis support
  openSpace?: boolean;         // Needs horizontal open room (not walled in)
  mustTouchWater?: boolean;    // Must touch water directly horizontally (Sugarcane)
  shallowWater?: boolean;      // Shallow standing water or very saturated soil (Rice)
  desertSandOnly?: boolean;    // Desert sand only, drowns easily if water > 5 (Cactus fruit)
  shadeOnly?: boolean;         // Darkness or shade, no direct sunlight (Mushrooms)
  regrows?: boolean;           // Perennial, regrows after harvest (Strawberries, Grapes, etc.)
  twoBlocksTall?: boolean;     // Grows 2 blocks tall when mature (Corn, Sunflower, Sugarcane)
  acidicConifer?: boolean;     // Thrives near conifers / acidic forest soil (Blueberries)
  restoresSoil?: boolean;      // Restores / enriches soil when harvested (Beans, Chickpeas)
  perennial?: boolean;         // Multi-season perennial
  notes?: string;
}

export interface CropConfig {
  id: string;
  name: string;
  seasons: Season[];           // Seasons in which the crop grows
  minWater: number;            // 0 - 13
  maxWater: number;            // 0 - 13
  allowedTemps: CropTemp[];    // 'C' (Cold), 'M' (Medium/Temperate), 'H' (Hot)
  growthSpeed: 'F' | 'M' | 'S';// Fast (2 ticks), Medium (3 ticks), Slow (4 ticks)
  needs: CropNeeds;
  foodName: string;
  seedName: string;
  color: string;               // Main visual color
  foodValue: number;           // Hunger / health restored
  wildBiomeHint: string;       // Biome where wild variant spawns
}

export const CROP_CONFIGS: CropConfig[] = [
  // ── Spring Crops ──
  {
    id: 'radishes',
    name: 'Radishes',
    seasons: [Season.SPRING],
    minWater: 3,
    maxWater: 13,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'F',
    needs: { notes: 'Fills the early-spring gap' },
    foodName: 'Radish',
    seedName: 'Radish Seeds',
    color: '#e11d48',
    foodValue: 12,
    wildBiomeHint: 'meadows'
  },
  {
    id: 'spinach',
    name: 'Spinach',
    seasons: [Season.SPRING],
    minWater: 3,
    maxWater: 13,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'F',
    needs: {},
    foodName: 'Spinach Leaves',
    seedName: 'Spinach Seeds',
    color: '#15803d',
    foodValue: 10,
    wildBiomeHint: 'meadows'
  },
  {
    id: 'lettuce',
    name: 'Lettuce',
    seasons: [Season.SPRING],
    minWater: 4,
    maxWater: 11,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'F',
    needs: { notes: 'Hates drought' },
    foodName: 'Crisp Lettuce',
    seedName: 'Lettuce Seeds',
    color: '#84cc16',
    foodValue: 8,
    wildBiomeHint: 'meadows'
  },
  {
    id: 'peas',
    name: 'Peas',
    seasons: [Season.SPRING],
    minWater: 4,
    maxWater: 13,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'F',
    needs: { trellis: true, notes: 'Requires trellis support' },
    foodName: 'Sweet Peas',
    seedName: 'Pea Pod Seeds',
    color: '#4ade80',
    foodValue: 12,
    wildBiomeHint: 'meadows'
  },
  {
    id: 'onions',
    name: 'Onions',
    seasons: [Season.SPRING],
    minWater: 3,
    maxWater: 12,
    allowedTemps: ['C', 'M', 'H'],
    growthSpeed: 'S',
    needs: { notes: 'Stores well' },
    foodName: 'Yellow Onion',
    seedName: 'Onion Seeds',
    color: '#ca8a04',
    foodValue: 14,
    wildBiomeHint: 'meadows_clump'
  },
  {
    id: 'potatoes',
    name: 'Potatoes',
    seasons: [Season.SPRING],
    minWater: 3,
    maxWater: 13,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'M',
    needs: { tilled: true, notes: 'Requires tilled soil' },
    foodName: 'Potato',
    seedName: 'Seed Potato',
    color: '#b45309',
    foodValue: 18,
    wildBiomeHint: 'mountains'
  },
  {
    id: 'cabbage',
    name: 'Cabbage',
    seasons: [Season.SPRING],
    minWater: 5,
    maxWater: 13,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'S',
    needs: { notes: 'Ferments well' },
    foodName: 'Cabbage Head',
    seedName: 'Cabbage Seeds',
    color: '#65a30d',
    foodValue: 16,
    wildBiomeHint: 'coast_cliffs'
  },
  {
    id: 'broccoli',
    name: 'Broccoli',
    seasons: [Season.SPRING],
    minWater: 5,
    maxWater: 12,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'M',
    needs: {},
    foodName: 'Broccoli Crown',
    seedName: 'Broccoli Seeds',
    color: '#166534',
    foodValue: 14,
    wildBiomeHint: 'coast_cliffs'
  },
  {
    id: 'cauliflower',
    name: 'Cauliflower',
    seasons: [Season.SPRING],
    minWater: 5,
    maxWater: 12,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'S',
    needs: {},
    foodName: 'Cauliflower Head',
    seedName: 'Cauliflower Seeds',
    color: '#f8fafc',
    foodValue: 15,
    wildBiomeHint: 'coast_cliffs'
  },
  {
    id: 'strawberries',
    name: 'Strawberries',
    seasons: [Season.SPRING],
    minWater: 4,
    maxWater: 9,
    allowedTemps: ['M'],
    growthSpeed: 'M',
    needs: { regrows: true, perennial: true, notes: 'Light water, regrows' },
    foodName: 'Wild Strawberry',
    seedName: 'Strawberry Seeds',
    color: '#ef4444',
    foodValue: 14,
    wildBiomeHint: 'forests'
  },
  {
    id: 'asparagus',
    name: 'Asparagus',
    seasons: [Season.SPRING],
    minWater: 3,
    maxWater: 11,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'S',
    needs: { regrows: true, perennial: true, notes: 'Perennial stalk' },
    foodName: 'Asparagus Spear',
    seedName: 'Asparagus Crowns',
    color: '#22c55e',
    foodValue: 16,
    wildBiomeHint: 'dunes'
  },
  {
    id: 'rhubarb',
    name: 'Rhubarb',
    seasons: [Season.SPRING],
    minWater: 4,
    maxWater: 12,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'M',
    needs: { regrows: true, perennial: true, notes: 'Perennial tart stalk' },
    foodName: 'Rhubarb Stalk',
    seedName: 'Rhubarb Crown',
    color: '#be123c',
    foodValue: 12,
    wildBiomeHint: 'mountains'
  },
  {
    id: 'garlic',
    name: 'Garlic',
    seasons: [Season.SPRING, Season.AUTUMN],
    minWater: 2,
    maxWater: 10,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'S',
    needs: { notes: 'Planted previous autumn or spring' },
    foodName: 'Garlic Bulb',
    seedName: 'Garlic Cloves',
    color: '#f5f5f4',
    foodValue: 12,
    wildBiomeHint: 'meadows_clump'
  },

  // ── Summer Crops ──
  {
    id: 'cucumbers',
    name: 'Cucumbers',
    seasons: [Season.SUMMER],
    minWater: 6,
    maxWater: 13,
    allowedTemps: ['M', 'H'],
    growthSpeed: 'F',
    needs: { notes: 'Pickling staple' },
    foodName: 'Cucumber',
    seedName: 'Cucumber Seeds',
    color: '#15803d',
    foodValue: 10,
    wildBiomeHint: 'warm_dry'
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    seasons: [Season.SUMMER],
    minWater: 5,
    maxWater: 13,
    allowedTemps: ['M', 'H'],
    growthSpeed: 'F',
    needs: { openSpace: true, notes: 'Needs open space' },
    foodName: 'Zucchini Squash',
    seedName: 'Zucchini Seeds',
    color: '#166534',
    foodValue: 14,
    wildBiomeHint: 'warm_dry'
  },
  {
    id: 'tomatoes',
    name: 'Tomatoes',
    seasons: [Season.SUMMER],
    minWater: 5,
    maxWater: 12,
    allowedTemps: ['M', 'H'],
    growthSpeed: 'M',
    needs: { trellis: true, notes: 'Requires trellis support' },
    foodName: 'Ripe Tomato',
    seedName: 'Tomato Seeds',
    color: '#dc2626',
    foodValue: 14,
    wildBiomeHint: 'warm_dry'
  },
  {
    id: 'beans',
    name: 'Beans',
    seasons: [Season.SUMMER],
    minWater: 4,
    maxWater: 13,
    allowedTemps: ['M', 'H'],
    growthSpeed: 'M',
    needs: { trellis: true, restoresSoil: true, notes: 'Trellis, restores soil' },
    foodName: 'Pole Beans',
    seedName: 'Bean Seeds',
    color: '#84cc16',
    foodValue: 15,
    wildBiomeHint: 'warm_dry'
  },
  {
    id: 'grapes',
    name: 'Grapes',
    seasons: [Season.SUMMER],
    minWater: 3,
    maxWater: 11,
    allowedTemps: ['M', 'H'],
    growthSpeed: 'S',
    needs: { trellis: true, regrows: true, perennial: true, notes: 'Trellis, perennial vine' },
    foodName: 'Sweet Grapes',
    seedName: 'Grapevine Cutting',
    color: '#7e22ce',
    foodValue: 16,
    wildBiomeHint: 'forest_edges'
  },
  {
    id: 'peppers',
    name: 'Peppers',
    seasons: [Season.SUMMER],
    minWater: 3,
    maxWater: 9,
    allowedTemps: ['M', 'H'],
    growthSpeed: 'M',
    needs: { notes: 'Light water, covered spot' },
    foodName: 'Bell Pepper',
    seedName: 'Pepper Seeds',
    color: '#ea580c',
    foodValue: 12,
    wildBiomeHint: 'warm_dry'
  },
  {
    id: 'herbs',
    name: 'Herbs',
    seasons: [Season.SUMMER],
    minWater: 3,
    maxWater: 9,
    allowedTemps: ['M', 'H'],
    growthSpeed: 'F',
    needs: { notes: 'Light water' },
    foodName: 'Aromatic Herbs',
    seedName: 'Herb Seeds',
    color: '#10b981',
    foodValue: 8,
    wildBiomeHint: 'forests'
  },
  {
    id: 'eggplant',
    name: 'Eggplant',
    seasons: [Season.SUMMER],
    minWater: 5,
    maxWater: 12,
    allowedTemps: ['M', 'H'],
    growthSpeed: 'S',
    needs: {},
    foodName: 'Glossy Eggplant',
    seedName: 'Eggplant Seeds',
    color: '#581c87',
    foodValue: 16,
    wildBiomeHint: 'warm_dry'
  },
  {
    id: 'corn',
    name: 'Corn',
    seasons: [Season.SUMMER],
    minWater: 4,
    maxWater: 13,
    allowedTemps: ['M', 'H'],
    growthSpeed: 'M',
    needs: { tilled: true, twoBlocksTall: true, notes: 'Tilled soil, 2 blocks tall' },
    foodName: 'Golden Maize',
    seedName: 'Corn Kernels',
    color: '#facc15',
    foodValue: 18,
    wildBiomeHint: 'warm_dry'
  },
  {
    id: 'melons',
    name: 'Melons',
    seasons: [Season.SUMMER],
    minWater: 7,
    maxWater: 13,
    allowedTemps: ['M', 'H'],
    growthSpeed: 'S',
    needs: { openSpace: true, notes: 'Open space, thirsty' },
    foodName: 'Melon Slice',
    seedName: 'Melon Seeds',
    color: '#22c55e',
    foodValue: 20,
    wildBiomeHint: 'warm_dry'
  },
  {
    id: 'rice',
    name: 'Rice',
    seasons: [Season.SUMMER],
    minWater: 9,
    maxWater: 13,
    allowedTemps: ['M', 'H'],
    growthSpeed: 'M',
    needs: { shallowWater: true, notes: 'Shallow standing water' },
    foodName: 'Rice Grains',
    seedName: 'Rice Seedlings',
    color: '#e2e8f0',
    foodValue: 14,
    wildBiomeHint: 'wetlands'
  },
  {
    id: 'sorghum',
    name: 'Sorghum/Millet',
    seasons: [Season.SUMMER],
    minWater: 1,
    maxWater: 7,
    allowedTemps: ['M', 'H'],
    growthSpeed: 'M',
    needs: { notes: 'Survives drought' },
    foodName: 'Sorghum Grain',
    seedName: 'Millet Seeds',
    color: '#d97706',
    foodValue: 14,
    wildBiomeHint: 'warm_dry'
  },
  {
    id: 'sunflowers',
    name: 'Sunflowers',
    seasons: [Season.SUMMER],
    minWater: 2,
    maxWater: 10,
    allowedTemps: ['M', 'H'],
    growthSpeed: 'M',
    needs: { twoBlocksTall: true, notes: 'Tall, seeds and oil' },
    foodName: 'Sunflower Seeds',
    seedName: 'Sunflower Seed Packet',
    color: '#fbbf24',
    foodValue: 10,
    wildBiomeHint: 'meadows'
  },
  {
    id: 'blueberries',
    name: 'Blueberries',
    seasons: [Season.SUMMER],
    minWater: 4,
    maxWater: 10,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'S',
    needs: { regrows: true, perennial: true, acidicConifer: true, notes: 'Perennial, acidic soil near conifers' },
    foodName: 'Wild Blueberries',
    seedName: 'Blueberry Cutting',
    color: '#2563eb',
    foodValue: 14,
    wildBiomeHint: 'conifer_forests'
  },
  {
    id: 'hops',
    name: 'Hops',
    seasons: [Season.SUMMER],
    minWater: 4,
    maxWater: 12,
    allowedTemps: ['M'],
    growthSpeed: 'M',
    needs: { trellis: true, notes: 'Trellis, brewing vine' },
    foodName: 'Fresh Hops',
    seedName: 'Hop Rhizome',
    color: '#84cc16',
    foodValue: 6,
    wildBiomeHint: 'forest_edges'
  },
  {
    id: 'flax',
    name: 'Flax',
    seasons: [Season.SUMMER],
    minWater: 3,
    maxWater: 11,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'F',
    needs: { notes: 'Textile cloth fiber' },
    foodName: 'Flax Fiber',
    seedName: 'Linseed Flax Seeds',
    color: '#38bdf8',
    foodValue: 6,
    wildBiomeHint: 'meadows'
  },
  {
    id: 'sugarcane',
    name: 'Sugarcane',
    seasons: [Season.SUMMER],
    minWater: 8,
    maxWater: 13,
    allowedTemps: ['M', 'H'],
    growthSpeed: 'M',
    needs: { mustTouchWater: true, twoBlocksTall: true, notes: 'Must touch water, tall' },
    foodName: 'Sugar Cane',
    seedName: 'Sugarcane Stalk',
    color: '#4ade80',
    foodValue: 8,
    wildBiomeHint: 'riverbanks'
  },

  // ── Autumn Crops ──
  {
    id: 'pumpkins',
    name: 'Pumpkins/Squash',
    seasons: [Season.AUTUMN],
    minWater: 4,
    maxWater: 13,
    allowedTemps: ['M'],
    growthSpeed: 'S',
    needs: { openSpace: true, notes: 'Needs open space' },
    foodName: 'Pumpkin Chunk',
    seedName: 'Pumpkin Seeds',
    color: '#f97316',
    foodValue: 18,
    wildBiomeHint: 'warm_dry'
  },
  {
    id: 'carrots',
    name: 'Carrots',
    seasons: [Season.AUTUMN],
    minWater: 3,
    maxWater: 12,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'M',
    needs: { tilled: true, notes: 'Requires tilled soil' },
    foodName: 'Crisp Carrot',
    seedName: 'Carrot Seeds',
    color: '#f97316',
    foodValue: 15,
    wildBiomeHint: 'meadows'
  },
  {
    id: 'beets',
    name: 'Beets',
    seasons: [Season.AUTUMN],
    minWater: 3,
    maxWater: 13,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'M',
    needs: {},
    foodName: 'Ruby Beet',
    seedName: 'Beet Seeds',
    color: '#9f1239',
    foodValue: 14,
    wildBiomeHint: 'shorelines'
  },
  {
    id: 'turnips',
    name: 'Turnips',
    seasons: [Season.AUTUMN],
    minWater: 3,
    maxWater: 13,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'F',
    needs: { notes: 'Hardy root' },
    foodName: 'White Turnip',
    seedName: 'Turnip Seeds',
    color: '#e2e8f0',
    foodValue: 14,
    wildBiomeHint: 'meadows'
  },
  {
    id: 'sweet_potatoes',
    name: 'Sweet Potatoes',
    seasons: [Season.AUTUMN],
    minWater: 4,
    maxWater: 12,
    allowedTemps: ['M', 'H'],
    growthSpeed: 'S',
    needs: { tilled: true, notes: 'Requires tilled soil' },
    foodName: 'Sweet Potato',
    seedName: 'Sweet Potato Slip',
    color: '#ea580c',
    foodValue: 18,
    wildBiomeHint: 'warm_dry'
  },
  {
    id: 'celery',
    name: 'Celery',
    seasons: [Season.AUTUMN],
    minWater: 7,
    maxWater: 13,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'S',
    needs: { notes: 'Thirsty stalk' },
    foodName: 'Celery Rib',
    seedName: 'Celery Seeds',
    color: '#84cc16',
    foodValue: 8,
    wildBiomeHint: 'wetlands'
  },
  {
    id: 'leeks',
    name: 'Leeks',
    seasons: [Season.AUTUMN],
    minWater: 3,
    maxWater: 12,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'S',
    needs: {},
    foodName: 'Leek Stalk',
    seedName: 'Leek Seeds',
    color: '#65a30d',
    foodValue: 12,
    wildBiomeHint: 'meadows_clump'
  },
  {
    id: 'wheat',
    name: 'Wheat',
    seasons: [Season.AUTUMN],
    minWater: 3,
    maxWater: 12,
    allowedTemps: ['M'],
    growthSpeed: 'M',
    needs: { tilled: true, notes: 'Requires tilled soil' },
    foodName: 'Wheat Sheaf',
    seedName: 'Wheat Seeds',
    color: '#eab308',
    foodValue: 12,
    wildBiomeHint: 'meadows'
  },
  {
    id: 'barley',
    name: 'Barley',
    seasons: [Season.AUTUMN],
    minWater: 2,
    maxWater: 11,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'M',
    needs: { notes: 'Tolerates poor soil' },
    foodName: 'Barley Ears',
    seedName: 'Barley Seeds',
    color: '#ca8a04',
    foodValue: 12,
    wildBiomeHint: 'meadows'
  },
  {
    id: 'oats',
    name: 'Oats',
    seasons: [Season.AUTUMN],
    minWater: 3,
    maxWater: 13,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'M',
    needs: { notes: 'Handles wet and cold' },
    foodName: 'Oat Panicle',
    seedName: 'Oat Seeds',
    color: '#fef08a',
    foodValue: 12,
    wildBiomeHint: 'meadows'
  },
  {
    id: 'rye',
    name: 'Rye',
    seasons: [Season.AUTUMN],
    minWater: 2,
    maxWater: 11,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'M',
    needs: { notes: 'Hardy grain' },
    foodName: 'Rye Spikes',
    seedName: 'Rye Seeds',
    color: '#a16207',
    foodValue: 12,
    wildBiomeHint: 'meadows'
  },
  {
    id: 'sugar_beets',
    name: 'Sugar Beets',
    seasons: [Season.AUTUMN],
    minWater: 3,
    maxWater: 12,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'M',
    needs: { tilled: true, notes: 'Requires tilled soil' },
    foodName: 'Sugar Beet',
    seedName: 'Sugar Beet Seeds',
    color: '#f1f5f9',
    foodValue: 12,
    wildBiomeHint: 'shorelines'
  },
  {
    id: 'fruit_trees',
    name: 'Fruit Trees (Apple/Plum/Pear)',
    seasons: [Season.AUTUMN],
    minWater: 3,
    maxWater: 12,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'S',
    needs: { regrows: true, perennial: true, notes: 'Perennial orchard sapling' },
    foodName: 'Orchard Fruit',
    seedName: 'Fruit Tree Sapling',
    color: '#dc2626',
    foodValue: 22,
    wildBiomeHint: 'forests'
  },
  {
    id: 'cranberries',
    name: 'Cranberries',
    seasons: [Season.AUTUMN],
    minWater: 9,
    maxWater: 13,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'M',
    needs: { shallowWater: true, notes: 'Standing-water bog' },
    foodName: 'Tart Cranberries',
    seedName: 'Cranberry Cutting',
    color: '#b91c1c',
    foodValue: 12,
    wildBiomeHint: 'wetlands'
  },
  {
    id: 'chickpeas',
    name: 'Chickpeas/Lentils',
    seasons: [Season.AUTUMN],
    minWater: 1,
    maxWater: 8,
    allowedTemps: ['M', 'H'],
    growthSpeed: 'M',
    needs: { restoresSoil: true, notes: 'Low water, restores soil' },
    foodName: 'Chickpeas & Lentils',
    seedName: 'Chickpea Seeds',
    color: '#d97706',
    foodValue: 16,
    wildBiomeHint: 'warm_dry'
  },

  // ── Winter Crops ──
  {
    id: 'kale',
    name: 'Kale',
    seasons: [Season.WINTER],
    minWater: 3,
    maxWater: 13,
    allowedTemps: ['C'],
    growthSpeed: 'M',
    needs: { notes: 'Sweeter after frost' },
    foodName: 'Frost-Kissed Kale',
    seedName: 'Kale Seeds',
    color: '#15803d',
    foodValue: 14,
    wildBiomeHint: 'coast_cliffs'
  },
  {
    id: 'parsnips',
    name: 'Parsnips',
    seasons: [Season.WINTER],
    minWater: 3,
    maxWater: 12,
    allowedTemps: ['C'],
    growthSpeed: 'S',
    needs: { tilled: true, notes: 'Requires tilled soil' },
    foodName: 'Parsnip Root',
    seedName: 'Parsnip Seeds',
    color: '#fef3c7',
    foodValue: 16,
    wildBiomeHint: 'mountains'
  },
  {
    id: 'brussels_sprouts',
    name: 'Brussels Sprouts',
    seasons: [Season.WINTER],
    minWater: 4,
    maxWater: 12,
    allowedTemps: ['C'],
    growthSpeed: 'S',
    needs: {},
    foodName: 'Brussels Sprouts',
    seedName: 'Sprout Seeds',
    color: '#4ade80',
    foodValue: 14,
    wildBiomeHint: 'coast_cliffs'
  },
  {
    id: 'winter_leeks',
    name: 'Winter Leeks',
    seasons: [Season.WINTER],
    minWater: 3,
    maxWater: 12,
    allowedTemps: ['C'],
    growthSpeed: 'S',
    needs: {},
    foodName: 'Winter Leek',
    seedName: 'Winter Leek Seeds',
    color: '#4d7c0f',
    foodValue: 14,
    wildBiomeHint: 'mountains'
  },
  {
    id: 'rutabaga',
    name: 'Rutabaga',
    seasons: [Season.WINTER],
    minWater: 3,
    maxWater: 13,
    allowedTemps: ['C'],
    growthSpeed: 'S',
    needs: { tilled: true, notes: 'Tilled, stores well' },
    foodName: 'Rutabaga Swede',
    seedName: 'Rutabaga Seeds',
    color: '#a855f7',
    foodValue: 18,
    wildBiomeHint: 'mountains'
  },
  {
    id: 'horseradish',
    name: 'Horseradish',
    seasons: [Season.WINTER],
    minWater: 2,
    maxWater: 10,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'S',
    needs: { regrows: true, perennial: true, notes: 'Perennial spicy root' },
    foodName: 'Horseradish Root',
    seedName: 'Horseradish Crown',
    color: '#e7e5e4',
    foodValue: 12,
    wildBiomeHint: 'mountains'
  },

  // ── Multi-season / Any-season Crops ──
  {
    id: 'winter_grain',
    name: 'Winter Wheat/Rye',
    seasons: [Season.AUTUMN, Season.WINTER, Season.SPRING],
    minWater: 3,
    maxWater: 12,
    allowedTemps: ['C', 'M'],
    growthSpeed: 'S',
    needs: { notes: 'Planted autumn, grows through the cold' },
    foodName: 'Hardy Winter Grain',
    seedName: 'Winter Grain Seeds',
    color: '#b45309',
    foodValue: 15,
    wildBiomeHint: 'meadows'
  },
  {
    id: 'mushrooms',
    name: 'Mushrooms',
    seasons: [Season.SPRING, Season.SUMMER, Season.AUTUMN, Season.WINTER],
    minWater: 5,
    maxWater: 11,
    allowedTemps: ['C', 'M', 'H'],
    growthSpeed: 'M',
    needs: { shadeOnly: true, notes: 'Darkness or shade, no direct sunlight' },
    foodName: 'Forest Mushroom',
    seedName: 'Mushroom Spores',
    color: '#78350f',
    foodValue: 12,
    wildBiomeHint: 'forests_caves'
  },
  {
    id: 'cactus_fruit',
    name: 'Cactus Fruit',
    seasons: [Season.SPRING, Season.SUMMER, Season.AUTUMN, Season.WINTER],
    minWater: 1,
    maxWater: 5,
    allowedTemps: ['H'],
    growthSpeed: 'S',
    needs: { desertSandOnly: true, notes: 'Desert sand only, drowns easily' },
    foodName: 'Sweet Cactus Fruit',
    seedName: 'Cactus Seeds',
    color: '#f43f5e',
    foodValue: 16,
    wildBiomeHint: 'desert_only'
  }
];

export const CROP_CONFIG_MAP: Map<string, CropConfig> = new Map(
  CROP_CONFIGS.map(c => [c.id, c])
);
